# 基础镜像nginx
FROM nginx:alpine
# 定义作者
MAINTAINER outsider<outsider@gmail.com>
# 设置时区

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

# 端口
EXPOSE 80

RUN echo 'dockerfile build images success!!'

